vagrant for local test working

diff --git a/cli/app/local/install/ansible b/cli/app/local/install/ansible
--- a/cli/app/local/install/ansible
+++ b/cli/app/local/install/ansible
@@ -13,6 +13,10 @@ function cleanup() {
 if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
     trap cleanup EXIT
 
+    # shellcheck disable=SC2154
+    path=$(${cli_name_app} zoptions rc read .dir)
+    cd "$path" || fatal "Failed to cd to $path"
+
     # Check if python3 is installed
     if ! command -v python3 &> /dev/null; then
         info "Python3 is not installed. Please install Python3 first."
@@ -29,13 +33,18 @@ if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
     fi
 
     # Create a virtual environment
-    python3 -m venv .venv
-    
+    if [[ ! -d .venv ]]; then
+        python3 -m venv .venv
+    else
+        info "Virtual environment already exists."
+    fi
+
     # shellcheck disable=SC1091
     source .venv/bin/activate
 
+    pip install --upgrade pip
     pip install ansible --no-input
     pip install ansible-creator --no-input
 
-    ansible-galaxy install -r kubernetes-playbook/requirements.yml
+    #ansible-galaxy install -r kubernetes-playbook/requirements.yml
 fi
