vagrant ça marche pas non plus ptdr le suicide

diff --git a/cli/app/local/ssh/create b/cli/app/local/ssh/create
--- a/cli/app/local/ssh/create
+++ b/cli/app/local/ssh/create
@@ -12,8 +12,9 @@ function cleanup() {
 if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
     trap cleanup EXIT
 
-    path=`$cli_name_app zoptions rc read .dir`
-    cd ${path}
+    # shellcheck disable=SC2154
+    path=$(${cli_name_app} zoptions rc read .dir)
+    cd "${path}" || fatal "Failed to cd to ${path}"
 
     # Create SSH key pair
     ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N "" -C "admin@admin.com"
