lint fix

diff --git a/cli/app/ansible/kube/install b/cli/app/ansible/kube/install
--- a/cli/app/ansible/kube/install
+++ b/cli/app/ansible/kube/install
@@ -3,6 +3,7 @@ set -uo pipefail
 IFS=$'\n\t'
 
 # Load utility methods
+# shellcheck disable=SC1091
 . "$ROOT_DIR/utils"
 
 function cleanup() {
@@ -12,10 +13,14 @@ function cleanup() {
 if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
     trap cleanup EXIT
 
-    path=`$cli_name_app zoptions rc read .dir`
-    cd "${path}"
+    # shellcheck disable=SC2154
+    path=$(${cli_name_app} zoptions rc read .dir)
+    cd "$path" || fatal "Failed to cd to $path"
 
     info "Launching ansible playbook to install kubernetes on hosts"
+
+    # shellcheck disable=SC1091
     source ".venv/bin/activate"
+
     ansible-playbook -i kubernetes-playbook/inventory.yml kubernetes-playbook/deploy_kubernetes.yml --ask-vault-pass
 fi
diff --git a/cli/app/local/ssh/deploy b/cli/app/local/ssh/deploy
--- a/cli/app/local/ssh/deploy
+++ b/cli/app/local/ssh/deploy
@@ -3,6 +3,7 @@ set -uo pipefail
 IFS=$'\n\t'
 
 # Load utility methods
+# shellcheck disable=SC1091
 . "$ROOT_DIR/utils"
 
 function cleanup() {
@@ -47,39 +48,34 @@ fi
 if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
     trap cleanup EXIT
 
-    path=`$cli_name_app zoptions rc read .dir`
-    cd "${path}"
+    # shellcheck disable=SC2154
+    path=$(${cli_name_app} zoptions rc read .dir)
+    cd "$path" || fatal "Failed to cd to $path"
 
     # Prompt for SSH user and IP address if not provided as arguments
     if [[ -z "$ssh_user" ]]; then
-        read -p "Enter the SSH user: " ssh_user
+        read -r -p "Enter the SSH user: " ssh_user
     fi
 
     if [[ -z "$ip_address" ]]; then
-        read -p "Enter the IP address: " ip_address
+        read -r -p "Enter the IP address: " ip_address
     fi
 
     # Copy the SSH public key to the remote host
-    ssh-copy-id -o StrictHostKeyChecking=no -i keys/id_rsa.pub "${ssh_user}@${ip_address}"
-
-    if [ $? -eq 0 ]; then
+    if ssh-copy-id -o StrictHostKeyChecking=no -i keys/id_rsa.pub "${ssh_user}@${ip_address}"; then
         echo "SSH key successfully copied to ${ssh_user}@${ip_address}"
     else
-        echo "Failed to copy SSH key. Please check the user and IP address and try again."
-        exit 1
+        fatal "Failed to copy SSH key"
     fi
 
     # Prompt for the sudo password
-    read -s -p "Enter sudo password for ${ssh_user}@${ip_address}: " sudo_pass
+    read -r -s -p "Enter sudo password for ${ssh_user}@${ip_address}: " sudo_pass
     echo ""
 
     # Configure passwordless sudo for the SSH user using the provided password
-    echo "${sudo_pass}" | ssh -o StrictHostKeyChecking=no "${ssh_user}@${ip_address}" "sudo -S bash -c \"echo '${ssh_user} ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/${ssh_user} && sudo chmod 440 /etc/sudoers.d/${ssh_user}\""
-
-    if [ $? -eq 0 ]; then
+    if echo "${sudo_pass}" | ssh -o StrictHostKeyChecking=no "${ssh_user}@${ip_address}" "sudo -S bash -c \"echo '${ssh_user} ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/${ssh_user} && sudo chmod 440 /etc/sudoers.d/${ssh_user}\""; then
         echo "Passwordless sudo configured for user '${ssh_user}' on ${ip_address}"
     else
-        echo "Failed to configure passwordless sudo for user '${ssh_user}' on ${ip_address}"
-        exit 1
+        fatal "Failed to configure passwordless sudo for user '${ssh_user}' on ${ip_address}"
     fi
 fi
diff --git a/cli/cli b/cli/cli
--- a/cli/cli
+++ b/cli/cli
@@ -1,13 +1,14 @@
 #!/usr/bin/env bash
 
 # Get the root directory of the script
-ROOT_DIR=$(dirname "$(readlink $0)")
-CLI_ENTRYPOINT=$(basename $0)
+ROOT_DIR="$(dirname "$(readlink -f "$0")")"
+CLI_ENTRYPOINT="$(basename "$0")"
 
 # Export the root directory for later use
 export ROOT_DIR
 
 # Include utility functions
+# shellcheck disable=SC1091
 . "$ROOT_DIR/utils"
 
 # Locate the correct command to execute by traversing the "app" directory
@@ -45,8 +46,8 @@ fi
 # If we don't find the exact command entered by the user, we display a warning.
 if [[ ! -f "$CMD_FILE" ]]; then
     "$ROOT_DIR/help" "$0" "${@:1:$((CMD_ARG_START-1))}"
-    >&2 echo -e "\033[31mThe command \033[36m$CLI_ENTRYPOINT ${@:1:$CMD_ARG_START}\033[39m was not found."
-    >&2 echo -e "We have displayed the help documentation for \033[36m$CLI_ENTRYPOINT ${@:1:$(($CMD_ARG_START-1))}\033[39m to assist you."
+    >&2 echo -e "\033[31mThe command \033[36m$CLI_ENTRYPOINT ${*:1:$CMD_ARG_START}\033[39m was not found."
+    >&2 echo -e "We have displayed the help documentation for \033[36m$CLI_ENTRYPOINT ${*:1:$((CMD_ARG_START-1))}\033[39m to assist you."
     exit 3
 fi
 
